### ISSUE TITLE
is this project still maintained?

### ISSUE THREAD

**Issue by berlinguyinca** [cibotech/evilplot#142]
we are seeing lots of errors and issues on the 0.8.1 version. Most notably in this section:

object Polygon {
  implicit val encoder: Encoder[Polygon] = Encoder.forProduct1("b") { x =>
    x.boundary
  }
  implicit val decoder: Decoder[Polygon] = Decoder.forProduct1("b")(
    (boundary: Seq[Point]) => new Polygon(boundary)
  )

  def clipped(boundary: Seq[Point], extent: Extent): Drawable = {
    Polygon(Clipping.clipPolygon(boundary, extent))
  }

  def apply(boundary: Seq[Point2d]): Drawable = {
    val minX = boundary.map(_.x).min
    val minY = boundary.map(_.y).min
    Translate(new Polygon(boundary.map { x =>
      Point(x.x - minX, x.y - minY)
    }), minX, minY)
  }

where minBy option should be used, since the boundary is for some reason empty a lot of times

**Comment by ahawkins318** [comment]
This project is no longer being actively developed. You may want to consider adding logic in the calling code to ensure you aren't passing in an empty `Seq` and to ensure that your boundary is within the `extent`. Here are some tests demonstrating the expected behavior: https://github.com/cibotech/evilplot/blob/0ff2f1c4257ff9fd19c2a70aa02a77a14aee0a5b/shared/src/test/scala/com/cibo/evilplot/geometry/ClippingSpec.scala#L138
